// Generated by CoffeeScript 1.3.3
(function() {
  var Context, coala, createRouter, entityMetaResolver, log, meta, metas, name, options, path, paths, router, _i, _j, _len, _ref,
    __slice = [].slice;

  Context = com.zyeeda.framework.web.SpringAwareJsgiServlet.Context;

  createRouter = require('coala/router').createRouter;

  coala = require('coala/config').coala;

  log = require('ringo/logging').getLogger(module.id);

  entityMetaResolver = Context.getInstance(module).getBeanByClass(com.zyeeda.framework.web.scaffold.EntityMetaResolver);

  router = exports.router = createRouter();

  metas = entityMetaResolver.resolveScaffoldEntities(coala.entityPackages);

  for (_i = 0, _len = metas.length; _i < _len; _i++) {
    meta = metas[_i];
    path = meta.path;
    path = path.replace(/(^\/)|(\/$)/g, '');
    _ref = path.split('/'), paths = 2 <= _ref.length ? __slice.call(_ref, 0, _j = _ref.length - 1) : (_j = 0, []), name = _ref[_j++];
    paths.push(coala.scaffoldFolderName);
    paths.push(name);
    path = paths.join('/');
    options = (function() {
      try {
        return require(path);
      } catch (e) {
        return {};
      }
    })();
    log.debug("find scaffolding entity:" + meta.entityClass + " bind to " + meta.path + ", with options:" + (JSON.stringify(options)));
    router.attachDomain(meta.path, meta.entityClass, options);
  }

}).call(this);
