// Generated by CoffeeScript 1.3.3
(function() {
  var Context, coala, createRouter, entityMetaResolver, generateForms, json, log, meta, metas, mountExtraRoutes, router, _fn, _i, _len,
    __slice = [].slice;

  Context = com.zyeeda.framework.web.SpringAwareJsgiServlet.Context;

  createRouter = require('coala/router').createRouter;

  coala = require('coala/config').coala;

  json = require('coala/response').json;

  generateForms = require('coala/scaffold/form-generator').generateForms;

  log = require('ringo/logging').getLogger(module.id);

  entityMetaResolver = Context.getInstance(module).getBeanByClass(com.zyeeda.framework.web.scaffold.EntityMetaResolver);

  router = exports.router = createRouter();

  metas = entityMetaResolver.resolveScaffoldEntities(coala.entityPackages);

  mountExtraRoutes = function(router, meta, options) {
    router.get('configuration/forms', function(request) {
      return json(generateForms(meta, options.labels, options.forms));
    });
    router.get('configuration/operators', function(request) {
      var operators;
      operators = options['operators'] || coala.defaultOperators;
      return json(operators);
    });
    router.get('configuration/grid', function(request) {
      var colModel, grid, name, value, _ref;
      grid = options['grid'];
      if (!grid && options.labels) {
        colModel = [];
        _ref = options.labels;
        for (name in _ref) {
          value = _ref[name];
          colModel.push({
            name: name,
            index: name,
            label: value
          });
        }
        grid = {
          colModel: colModel
        };
      }
      return json(grid);
    });
    return router.get('configuration/:name', function(request, name) {
      return json(options[name]);
    });
  };

  _fn = function(meta, mountExtraRoutes) {
    var doWithRouter, name, options, path, paths, _j, _ref;
    path = meta.path;
    path = path.replace(/(^\/)|(\/$)/g, '');
    _ref = path.split('/'), paths = 2 <= _ref.length ? __slice.call(_ref, 0, _j = _ref.length - 1) : (_j = 0, []), name = _ref[_j++];
    paths.push(coala.scaffoldFolderName);
    paths.push(name);
    path = paths.join('/');
    options = (function() {
      try {
        return require(path);
      } catch (e) {
        return {};
      }
    })();
    log.debug("find scaffolding entity:" + meta.entityClass + " bind to " + meta.path + ", with options:" + (JSON.stringify(options)));
    doWithRouter = options.doWithRouter || function() {};
    options.doWithRouter = function(router) {
      doWithRouter(router);
      return mountExtraRoutes(router, meta, options);
    };
    return router.attachDomain(meta.path, meta.entityClass, options);
  };
  for (_i = 0, _len = metas.length; _i < _len; _i++) {
    meta = metas[_i];
    _fn(meta, mountExtraRoutes);
  }

}).call(this);
