// Generated by CoffeeScript 1.3.3
(function() {
  var createService, mark, type,
    __slice = [].slice;

  mark = require('coala/mark').mark;

  createService = require('coala/service').createService;

  type = require('coala/util').type;

  exports.createService = function(entityClass, entityMeta) {
    var baseService, service;
    baseService = createService();
    service = {
      entityClass: entityClass,
      list: function(entity, options) {
        var manager;
        manager = baseService.createManager(service.entityClass);
        return manager.findByExample(entity, options);
      },
      get: function(id) {
        var manager;
        manager = baseService.createManager(service.entityClass);
        return manager.find(id);
      },
      create: mark('tx').on(function(entity) {
        var fieldManager, fieldMeta, manager, value, values, _i, _j, _len, _len1, _ref, _ref1;
        manager = baseService.createManager(service.entityClass);
        entity = manager.save(entity);
        _ref = entityMeta.getFields();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          fieldMeta = _ref[_i];
          if (fieldMeta.isOneToMany()) {
            values = entity[fieldMeta.name];
            if (values !== null && values.isEmpty && !values.isEmpty()) {
              fieldManager = baseService.createManager(fieldMeta.manyType);
              _ref1 = values.toArray();
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                value = _ref1[_j];
                value[fieldMeta.mappedBy] = entity;
                fieldManager.merge(value);
              }
            }
          }
        }
        return entity;
      }),
      update: mark('tx').on(function(id, fn) {
        var entity, manager;
        manager = baseService.createManager(service.entityClass);
        entity = manager.find(id);
        fn(entity, service);
        return manager.merge(entity);
      }),
      remove: mark('tx').on(function() {
        var id, manager;
        id = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        manager = baseService.createManager(service.entityClass);
        manager.removeById.apply(manager, id);
        if (id.length === 1) {
          return id[0];
        } else {
          return id;
        }
      })
    };
    return service;
  };

}).call(this);
