// Generated by CoffeeScript 1.3.3
(function() {
  var createService, mark,
    __slice = [].slice;

  mark = require('coala/mark').mark;

  createService = require('coala/service').createService;

  exports.createService = function(entityClass) {
    var baseService, service;
    baseService = createService();
    service = {
      entityClass: entityClass,
      list: function(entity, options) {
        var manager;
        manager = baseService.createManager(service.entityClass);
        return manager.findByExample(entity, options);
      },
      get: function(id) {
        var manager;
        manager = baseService.createManager(service.entityClass);
        return manager.find(id);
      },
      create: mark('tx').on(function(entity) {
        var manager;
        manager = baseService.createManager(service.entityClass);
        return manager.save(entity);
      }),
      update: mark('tx').on(function(id, fn) {
        var entity, manager;
        manager = baseService.createManager(service.entityClass);
        entity = manager.find(id);
        fn(entity, service);
        return manager.merge(entity);
      }),
      remove: mark('tx').on(function() {
        var id, manager;
        id = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        manager = baseService.createManager(service.entityClass);
        manager.removeById.apply(manager, id);
        if (id.length === 1) {
          return id[0];
        } else {
          return id;
        }
      })
    };
    return service;
  };

}).call(this);
