// Generated by CoffeeScript 1.4.0
(function() {
  var mark, ok;

  mark = require('coala/mark').mark;

  ok = require('assert').ok;

  exports.testMark = function() {
    return ok(mark !== null);
  };

}).call(this);
