// Generated by CoffeeScript 1.3.3
(function() {
  var defaultConfigure, log, name, objects, projectLevelConfigure, value, _ref;

  objects = require('coala/util').objects;

  log = require('ringo/logging').getLogger(module.id);

  projectLevelConfigure = (function() {
    try {
      return require('config');
    } catch (e) {
      return {};
    }
  })();

  defaultConfigure = {
    development: true,
    orms: ['src/main/resources/META-INF/orms/orm.xml'],
    scaffoldFolderName: '__scaffold__',
    serviceFolderName: '__services__',
    managerFolderName: '__managers__',
    routerFoldername: '__routers__',
    servicePathSeperator: ':',
    defaultPageSize: 10,
    dateFormat: 'yyyy-MM-dd',
    booleanFieldPickerSource: [
      {
        id: true,
        text: '是'
      }, {
        id: false,
        text: '否'
      }
    ],
    defaultOperators: {
      add: {
        label: '添加',
        icon: 'icon-plus'
      },
      edit: {
        label: '编辑',
        icon: 'icon-edit'
      },
      del: {
        label: '删除',
        icon: 'icon-minus'
      },
      show: {
        label: '查看',
        icon: 'icon-eye-open'
      }
    },
    extractPaginationInfo: function(params) {
      var currentPage, pageSize;
      pageSize = params['_pageSize'];
      currentPage = params['_page'];
      if (!currentPage) {
        return null;
      }
      delete params['_pageSize'];
      delete params['_page'];
      return {
        firstResult: (currentPage - 1) * pageSize,
        maxResults: pageSize,
        currentPage: currentPage
      };
    },
    generateListResult: function(results, currentPage, pageSize, recordCount, pageCount) {
      return {
        results: results,
        page: currentPage,
        recordCount: recordCount,
        pageCount: pageCount
      };
    },
    extractOrderInfo: function(params) {
      var o, order, orders, result, s, ts, _i, _len;
      orders = params['_order'];
      if (!orders) {
        return null;
      }
      delete params['_order'];
      orders = orders.split(',');
      result = [];
      for (_i = 0, _len = orders.length; _i < _len; _i++) {
        order = orders[_i];
        if (order.length === 0) {
          continue;
        }
        ts = order.split('-');
        s = ts.length === 1 ? 'asc' : ts[1];
        o = {};
        o[ts[0]] = s;
        result.push(o);
      }
      return result;
    }
  };

  exports.coala = objects.extend(defaultConfigure, projectLevelConfigure.coala);

  _ref = exports.coala;
  for (name in _ref) {
    value = _ref[name];
    log.debug("environment variable " + name + ":" + value);
  }

}).call(this);
