// Generated by CoffeeScript 1.3.3
(function() {
  var coala;

  coala = require('coala/config').coala;

  exports.mountTo = function(router) {
    router.mount('/scaffold', 'coala/scaffold/router');
    if (coala.development) {
      router.mount('/helper', 'coala/frontend-development-helper-router');
    }
    return router;
  };

}).call(this);
