// Generated by CoffeeScript 1.3.3
(function() {
  var getLogger;

  getLogger = require('ringo/logging').getLogger;

  exports.createLogger = function(moduleId) {
    return getLogger(moduleId);
  };

}).call(this);
