{exec} = require 'child_process'

task 'build', 'compile all server side coffees to js files', ->
    exec 'coffee -o src/main/resources/ -c src/main/coffee/', (err, stdout, stderr) ->
        console.log stdout + stderr

task 'watch', 'watch for server side coffee file changes', ->
    exec 'coffee -o src/main/resources/ -cw src/main/coffee/', (err, stdout, stderr) ->
        console.log err
        console.log stdout + stderr
