// Generated by CoffeeScript 1.3.3
(function() {
  var type;

  type = require('coala/util').type;

  exports.handler = function(context, attributes, fn, args) {
    var beans, name, _i, _len;
    beans = [];
    for (_i = 0, _len = attributes.length; _i < _len; _i++) {
      name = attributes[_i];
      beans.push((type(name) === 'string' ? context.getBean : context.getBeanByClass).call(context, name));
    }
    args = beans.concat(args);
    return fn.apply(null, args);
  };

}).call(this);
