// Generated by CoffeeScript 1.3.3

/*
# mark('knowledge', { sessionId: 123 }).on(function (ksession) { ... });
*/


(function() {
  var tx;

  tx = require('coala/tx').tx;

  exports.handler = function(context, attributes, fn, args) {
    var knowledgeService, options, sessionId;
    knowledgeService = context.getBean('knowledgeService');
    options = attributes[0] || {};
    sessionId = options.sessionId;
    return tx(function() {
      var ksession;
      ksession = sessionId ? knowledgeService.getKnowledgeSession(sessionId) : knowledgeService.createKnowledgeSession();
      args.unshift(ksession);
      return fn.apply(null, args);
    });
  };

}).call(this);
