// Generated by CoffeeScript 1.3.3
(function() {
  var createService, type;

  type = require('coala/util').type;

  createService = require('coala/process-service').createService;

  exports.handler = function(context, attributes, fn, args) {
    args.push(createService());
    return fn.apply(null, args);
  };

}).call(this);
