// Generated by CoffeeScript 1.3.3
(function() {
  var coala, paths, type, _ref;

  _ref = require('coala/util'), type = _ref.type, paths = _ref.paths;

  coala = require('coala/config').coala;

  exports.handler = function(context, attributes, fn, args) {
    var m, name, names, services, _i, _len;
    services = [];
    for (_i = 0, _len = attributes.length; _i < _len; _i++) {
      m = attributes[_i];
      names = m.split(coala.servicePathSeperator);
      if (names.length !== 2) {
        throw new Error("illegal service path: " + m + ", module:serviceName");
      }
      name = paths.join(names[0], coala.serviceFolderName, names[1]);
      services.push(require(name).createService());
    }
    args = services.concat(args);
    return fn.apply(null, args);
  };

}).call(this);
