// Generated by CoffeeScript 1.3.3
(function() {
  var tx;

  tx = require('coala/tx').tx;

  exports.handler = function(context, attributes, fn, args) {
    var needStatus, options;
    options = attributes[0] || {};
    needStatus = options.needStatus;
    options.callback = function(status) {
      if (needStatus === true) {
        args.unshift(status);
      }
      return fn.apply(null, args);
    };
    return tx(options);
  };

}).call(this);
